<?php
/** Original content, imported once into native WordPress posts. */
defined( 'ABSPATH' ) || exit;
return array(
'services' => array( array(
'title' => 'Marketing',
'description' => 'From sharp strategy to always-on execution — campaigns calibrated to move the needle.',
'tag' => 'Marketing',
'image' => 'projects/sme-bank-1.jpg',
'disciplines' => array( 'Strategy', 'Digital', 'Social', 'Media Planning', 'Campaigns', 'Reports' ),
), array(
'title' => 'Event Management',
'description' => 'Flagship launches, conferences and concert-scale activations — concept through closeout.',
'tag' => 'Events',
'image' => 'projects/ufc-1.jpg',
'disciplines' => array( 'Concept', '3D Design', 'Production', 'Entertainment', 'PR', 'Concierge' ),
), array(
'title' => 'Branding',
'description' => 'Names, identities and systems built to scale — not just to launch.',
'tag' => 'Branding',
'image' => 'projects/briefill-1.jpg',
'disciplines' => array( 'Naming', 'Identity', 'Guidelines', 'Applications', 'Collateral', 'Rebrands' ),
), array(
'title' => 'Content',
'description' => 'Words and storyboards that move people to act — in Arabic, English, and any channel.',
'tag' => 'Content',
'image' => 'projects/moh-1.jpg',
'disciplines' => array( 'Editorial', 'Concepts', 'Multilingual', 'Scripts', 'Brand Voice', 'Reports' ),
), array(
'title' => 'Animation',
'description' => 'Motion that explains, sells and makes a screen worth pausing for.',
'tag' => 'Animation',
'image' => 'projects/go-telecom-3.jpg',
'disciplines' => array( 'Motion Graphics', 'Montage', 'Infographics', 'Storyboards', 'Hero Films', 'Event Reels' ),
), array(
'title' => 'Website & Apps',
'description' => 'Strategy, design and development for digital homes that actually perform.',
'tag' => 'Digital',
'image' => 'projects/pointsgram-1.jpg',
'disciplines' => array( 'UX / UI', 'Web Dev', 'App Dev', 'Support', 'Monthly Updates', 'Maintenance' ),
) ),
'work' => array( array(
'title' => 'SAB Innovation Centre',
'cat' => 'Branding · Campaign',
'filters' => array( 'branding', 'campaign' ),
'meta' => array( '2024', 'Banking', 'Riyadh' ),
'desc' => 'Identity system, brand campaign and out-of-home executions for SAB\'s flagship innovation hub in Riyadh. We led the creative concept under the rallying line "Power Up The Future" — translating it across billboard mockups, opening-day brand activation and a launch event for press and stakeholders.',
'scope' => array( 'Brand identity', 'Campaign concept', 'OOH design', 'Event activation', 'Production', 'Photography' ),
'images' => array( 'projects/sab-1.jpg', 'projects/sab-2.jpg' ),
'brief' => 'Launch campaign and OOH for SAB\'s flagship innovation hub.',
'slug' => 'sab',
'home' => array(
'title' => 'SAB Innovation Centre',
'brief' => 'Identity, "Power Up The Future" launch campaign and out-of-home executions for SAB\'s flagship innovation hub in Riyadh.',
'mark' => 'Power Up',
'wide' => true,
'order' => 1,
'description' => 'Identity system, brand campaign and out-of-home executions for SAB\'s flagship innovation hub in Riyadh. We led the creative concept under the rallying line "Power Up The Future" — translating it across billboard mockups, opening-day brand activation and a launch event for press and stakeholders.',
),
), array(
'title' => 'GO Telecom · LEAP 2025',
'cat' => 'Exhibition · Campaign',
'filters' => array( 'events', 'campaign', 'digital' ),
'meta' => array( '2025', 'Telecom' ),
'desc' => 'Full pavilion design, brand activation and integrated campaign for GO Telecom at LEAP 2025 — the largest tech conference in the kingdom. Scope spanned 3D booth design, interactive kiosks, social rollout, and OOH support across Riyadh.',
'scope' => array( '3D design & rendering', 'Booth production', 'Interactive kiosks', 'Social campaign', 'OOH', 'Content' ),
'images' => array( 'projects/go-telecom-1.jpg', 'projects/go-telecom-2.jpg', 'projects/go-telecom-3.jpg' ),
'brief' => 'Pavilion + activation + integrated campaign at LEAP 2025.',
'slug' => 'go',
'home' => array(
'title' => 'GO Telecom · LEAP 2025',
'brief' => 'Pavilion design, brand activation and integrated campaign for the kingdom\'s largest tech conference.',
'mark' => 'GO',
'wide' => false,
'order' => 2,
'description' => 'Full pavilion design, brand activation and integrated campaign for GO Telecom at LEAP 2025 — the largest tech conference in the kingdom. Scope spanned 3D booth design, interactive kiosks, social rollout, and OOH support across Riyadh.',
),
), array(
'title' => 'UFC Fight Night · Riyadh',
'cat' => 'Event · Activation',
'filters' => array( 'events', 'activation' ),
'meta' => array( '2024', 'Sports' ),
'desc' => 'Two large-scale fan activations during UFC Fight Night Riyadh, produced in partnership with Sela: the <strong>Ultimate Food Challenge</strong> in a cage-style ring, and the <strong>Score &amp; Knock The Door</strong> strength tester.',
'scope' => array( 'Activation concept', 'Structural design', 'Branded production', 'On-site operations', 'Talent management' ),
'images' => array( 'projects/ufc-1.jpg', 'projects/five-vs-five-1.jpg', 'projects/ring-of-fire-1.jpg' ),
'brief' => 'Two activations at UFC Fight Night Riyadh.',
'slug' => 'ufc',
'home' => array(
'title' => 'UFC Fight Night · Riyadh',
'brief' => 'Two large-scale fan activations — Ultimate Food Challenge and Score & Knock The Door — produced in partnership with Sela.',
'mark' => 'UFC',
'wide' => true,
'order' => 6,
'description' => 'Two large-scale fan activations during UFC Fight Night Riyadh, produced in partnership with Sela: the <strong>Ultimate Food Challenge</strong> in a cage-style ring, and the <strong>Score &amp; Knock The Door</strong> strength tester. Scope included structural design, branded set production, talent and operations.',
),
), array(
'title' => 'Centrepoint · Ramadan + Homecentre Launch',
'cat' => 'Activation · Retail',
'filters' => array( 'activation', 'retail' ),
'meta' => array( '2024', 'Retail' ),
'desc' => 'Multi-mall Ramadan campaign for Centrepoint plus the regional grand opening for a new Homecentre store — including talent, parade, DJ, ribbon-cutting and full event production.',
'scope' => array( 'Retail campaign', 'Mall activation', 'Parade & performers', 'Talent management', 'Grand opening production' ),
'images' => array( 'projects/centrepoint-1.jpg', 'projects/centrepoint-2.jpg' ),
'brief' => 'Ramadan retail campaign and Homecentre grand opening.',
'slug' => 'centrepoint',
'home' => array(
'title' => 'Centrepoint · Ramadan & Homecentre Launch',
'brief' => 'Multi-mall Ramadan campaign and the regional grand opening for a new Homecentre store.',
'mark' => 'Centrepoint',
'wide' => false,
'order' => 8,
'description' => 'Multi-mall Ramadan campaign for Centrepoint plus the regional grand opening for a new Homecentre store — including talent, parade, DJ, ribbon-cutting and full event production.',
),
), array(
'title' => 'CR7 · Advanced Recovery',
'cat' => 'Campaign · Product',
'filters' => array( 'campaign' ),
'meta' => array( '2024', 'Sports & Wellness' ),
'desc' => 'Brand campaign and physical venue work for CR7\'s Advanced Recovery for Athletes — product launch films, athlete sessions and on-site branded experience.',
'scope' => array( 'Brand campaign', 'Film production', 'Athlete sessions', 'Venue branding' ),
'images' => array( 'projects/cr7-1.jpg', 'projects/cr7-2.jpg' ),
'brief' => '"Developed for CR7 and athletes like you" campaign.',
'slug' => 'cr7',
'home' => array(
'title' => 'CR7 · Advanced Recovery',
'brief' => 'Campaign and venue branding for CR7\'s Advanced Recovery for Athletes — product films and on-site experience.',
'mark' => 'CR7',
'wide' => false,
'order' => 7,
'description' => 'Brand campaign and physical venue work for CR7\'s Advanced Recovery for Athletes — product launch films, athlete sessions and on-site branded experience.',
),
), array(
'title' => 'SME Bank',
'cat' => 'Digital · Social',
'filters' => array( 'digital' ),
'meta' => array( '2023–25', 'Banking' ),
'desc' => 'Long-term creative partner for Saudi Arabia\'s SME-focused bank — always-on social, monthly editorial calendars, campaign creative and ongoing digital design work supporting their Vision 2030 mandate.',
'scope' => array( 'Social strategy', 'Editorial content', 'Campaign creative', 'Multilingual copy', 'Reporting' ),
'images' => array( 'projects/sme-bank-1.jpg', 'projects/sme-bank-2.jpg' ),
'brief' => 'Always-on social and digital identity for SME Bank.',
'slug' => 'sme',
'home' => array(
'title' => 'SME Bank',
'brief' => 'Always-on social, monthly editorial and digital design for Saudi Arabia\'s SME-focused bank.',
'mark' => 'SME',
'wide' => false,
'order' => 3,
'description' => 'Long-term creative partner for Saudi Arabia\'s SME-focused bank — always-on social, monthly editorial calendars, campaign creative and ongoing digital design work supporting their Vision 2030 mandate.',
),
), array(
'title' => 'SARCC · Thriving Together',
'cat' => 'Event · Branding',
'filters' => array( 'events', 'branding' ),
'meta' => array( '2024', 'Construction' ),
'desc' => 'Branding system and full event activation for SARCC\'s annual flagship gathering. From entrance arch to merchandise, photo backdrop and stakeholder content — produced under the line "Thriving Together."',
'scope' => array( 'Event identity', 'Set & arch design', 'Merchandise', 'Step-and-repeat', 'Production' ),
'images' => array( 'projects/sarcc-1.jpg' ),
'brief' => 'Annual flagship event with full brand activation.',
'slug' => 'sarcc',
'home' => array(
'title' => 'SARCC "Thriving Together"',
'brief' => 'Branding system and full event activation for SARCC\'s annual flagship gathering.',
'mark' => 'Thriving',
'wide' => false,
'order' => 5,
'description' => 'Branding system and full event activation for SARCC\'s annual flagship gathering. From entrance arch to merchandise, photo backdrop and stakeholder content — produced under the line "Thriving Together."',
),
), array(
'title' => 'MBSC · Class of 2024',
'cat' => 'Event · Production',
'filters' => array( 'events' ),
'meta' => array( '2024', 'Education' ),
'desc' => 'Concept, set design and full production of Prince Mohammed Bin Salman College\'s commencement ceremony, including stage design, screen content, graduate merchandise and supporting communications.',
'scope' => array( 'Event concept', 'Stage & set design', 'Screen content', 'Merchandise', 'Production' ),
'images' => array( 'projects/mbsc-1.jpg' ),
'brief' => 'Commencement ceremony for MBSC\'s class of 2024.',
'slug' => 'mbsc',
'home' => array(
'title' => 'MBSC · Class of 2024',
'brief' => 'Concept, set design and production for Prince Mohammed Bin Salman College\'s commencement ceremony.',
'mark' => 'MBSC',
'wide' => false,
'order' => 9,
'description' => 'Concept, set design and full production of Prince Mohammed Bin Salman College\'s commencement ceremony, including stage design, screen content, graduate merchandise and supporting communications.',
),
), array(
'title' => 'Boston Scientific',
'cat' => 'Event · PR',
'filters' => array( 'events' ),
'meta' => array( '2024', 'Healthcare', 'Jeddah' ),
'desc' => 'Medical-leadership gathering for Boston Scientific at Nozomi, Jeddah. We delivered concept, branded environment design, production, hospitality coordination and a full post-event report.',
'scope' => array( 'Event concept', 'Venue branding', 'Production', 'Hospitality', 'PR coordination', 'Reporting' ),
'images' => array( 'projects/boston-1.jpg' ),
'brief' => 'Medical-leadership gathering at Nozomi, Jeddah.',
'slug' => 'boston',
'home' => array(
'title' => 'Boston Scientific',
'brief' => 'Medical-leadership gathering at Nozomi — concept, production, hospitality and post-event reporting.',
'mark' => 'Boston',
'wide' => false,
'order' => 4,
'description' => 'Medical-leadership gathering for Boston Scientific at Nozomi, Jeddah. We delivered concept, branded environment design, production, hospitality coordination and a full post-event report.',
),
), array(
'title' => 'Al Khorayef Water & Power',
'cat' => 'Exhibition · Booth',
'filters' => array( 'events' ),
'meta' => array( '2024', 'Industrial' ),
'desc' => 'Custom exhibition stand and brochure design for Al Khorayef\'s water and power technologies presence — including curved overhead lighting structure, demo zone and printed collateral.',
'scope' => array( 'Booth design', 'Lighting', 'Brochure design', 'On-site production' ),
'images' => array( 'projects/khorayef-1.jpg' ),
'brief' => 'Exhibition stand for Al Khorayef water & power.',
'slug' => 'khorayef',
'home' => array(
),
), array(
'title' => 'Ministry of Health · Plasma Awareness',
'cat' => 'Campaign · OOH',
'filters' => array( 'campaign', 'digital' ),
'meta' => array( '2024', 'Government' ),
'desc' => 'Public awareness campaign for the Ministry of Health on the importance of blood plasma donation — billboard executions, social posts and information graphics in both Arabic and English.',
'scope' => array( 'Campaign concept', 'OOH design', 'Social content', 'Multilingual copy', 'Infographics' ),
'images' => array( 'projects/moh-1.jpg', 'projects/moh-2.jpg' ),
'brief' => 'Public awareness campaign on plasma donation.',
'slug' => 'moh',
'home' => array(
),
), array(
'title' => 'Altamayyuz Academy',
'cat' => 'Campaign · Social',
'filters' => array( 'campaign', 'digital' ),
'meta' => array( '2022', 'Education' ),
'desc' => 'Launch communications for the Altamayyuz Excellence Academy in partnership with major financial institutions including Aramco, SNB, Deloitte, KPMG and IE Business School.',
'scope' => array( 'Launch campaign', 'Social content', 'Partner communications', 'Multilingual copy' ),
'images' => array( 'projects/altamayyuz-1.jpg' ),
'brief' => 'Launch comms for the Excellence Academy.',
'slug' => 'altamayyuz',
'home' => array(
),
), array(
'title' => 'femi9 · Mamlakati Collection',
'cat' => 'Retail · Activation',
'filters' => array( 'retail', 'activation' ),
'meta' => array( '2024', 'Fashion' ),
'desc' => 'In-store activation for femi9\'s Mamlakati Collection — themed retail environment, mannequin styling, customer experience design and on-site photography.',
'scope' => array( 'Retail activation', 'Set design', 'Styling', 'Photography', 'On-site production' ),
'images' => array( 'projects/femi9-1.jpg' ),
'brief' => 'In-store activation for the Mamlakati Collection.',
'slug' => 'femi9',
'home' => array(
),
), array(
'title' => 'BMW · Naghi Motors',
'cat' => 'Activation · Showroom',
'filters' => array( 'activation', 'retail' ),
'meta' => array( '2024', 'Automotive' ),
'desc' => 'Concept and 3D rendering for a BMW showroom activation — feature vehicle staging, lighting design and customer journey through the new range.',
'scope' => array( '3D design', 'Showroom staging', 'Lighting', 'Production' ),
'images' => array( 'projects/bmw-1.jpg' ),
'brief' => 'BMW range showroom staging and activation.',
'slug' => 'bmw',
'home' => array(
),
), array(
'title' => 'Ford · New Everest',
'cat' => 'Event · Product Launch',
'filters' => array( 'events', 'activation' ),
'meta' => array( '2024', 'Automotive' ),
'desc' => 'Product launch event for the New Ford Everest at Naghi Motors — venue branding, hospitality, customer test-drive experience and supporting comms.',
'scope' => array( 'Event concept', 'Venue branding', 'Hospitality', 'Test-drive experience', 'Photography' ),
'images' => array( 'projects/ford-1.jpg' ),
'brief' => 'New Everest launch with Naghi Motors.',
'slug' => 'ford',
'home' => array(
),
), array(
'title' => 'MINI Cooper · Showroom',
'cat' => 'Branding · 3D',
'filters' => array( 'branding', 'retail' ),
'meta' => array( '2024', 'Automotive' ),
'desc' => '3D-rendered concept for a new MINI Cooper showroom and customer lounge — playful colour-blocked interior, café space and feature vehicle island.',
'scope' => array( '3D design', 'Interior concept', 'Customer journey', 'Brand application' ),
'images' => array( 'projects/mini-1.jpg' ),
'brief' => 'MINI showroom and lounge concept.',
'slug' => 'mini',
'home' => array(
),
), array(
'title' => 'Ring of Fire · Fury vs Usyk',
'cat' => 'Activation · Sports',
'filters' => array( 'activation', 'events' ),
'meta' => array( '2024', 'Sports' ),
'desc' => 'Three Olives\' Ring of Fire fan activation around the Fury vs Usyk fight — branded boxing-themed environment, punch-bag interaction and photo moments produced with Sela.',
'scope' => array( 'Activation concept', 'Branded environment', 'Interactive game', 'On-site operations' ),
'images' => array( 'projects/ring-of-fire-1.jpg' ),
'brief' => 'Ring of Fire fan activation for Fury vs Usyk.',
'slug' => 'ring-of-fire',
'home' => array(
),
), array(
'title' => '5 vs 5 · Punch Your Punch',
'cat' => 'Activation · Sports',
'filters' => array( 'activation', 'events' ),
'meta' => array( '2024', 'Sports' ),
'desc' => '"Punch Your Punch" boxing-card themed fan activation produced with Sela and Three Olives — twin punch-bag stations, branded scorecards and photo opportunities.',
'scope' => array( 'Activation concept', 'Branded set', 'Interactive scoring', 'On-site operations' ),
'images' => array( 'projects/five-vs-five-1.jpg' ),
'brief' => 'Twin-station boxing activation with Sela.',
'slug' => 'five-vs-five',
'home' => array(
),
), array(
'title' => 'Sushi Library',
'cat' => 'Activation · Hospitality',
'filters' => array( 'activation', 'retail' ),
'meta' => array( '2024', 'F&B' ),
'desc' => 'Japanese-themed launch activation for Sushi Library — kimono talent, cherry-blossom set design, themed merchandise and immersive customer photo experience.',
'scope' => array( 'Themed set design', 'Talent & costume', 'Merchandise', 'Photography', 'On-site operations' ),
'images' => array( 'projects/sushi-1.jpg' ),
'brief' => 'Japanese-themed restaurant launch activation.',
'slug' => 'sushi',
'home' => array(
),
), array(
'title' => 'SJP by Sarah Jessica Parker',
'cat' => 'Retail · Launch',
'filters' => array( 'retail', 'activation' ),
'meta' => array( '2024', 'Fashion' ),
'desc' => 'Boutique launch and styling event for SJP by Sarah Jessica Parker in KSA — red-carpet entrance, in-store styling sessions and influencer programming.',
'scope' => array( 'Launch event', 'Styling sessions', 'Influencer programme', 'Photography' ),
'images' => array( 'projects/sjp-1.jpg' ),
'brief' => 'Boutique launch and styling event in KSA.',
'slug' => 'sjp',
'home' => array(
),
), array(
'title' => 'Radisson Blu · Always-on',
'cat' => 'Digital · Social',
'filters' => array( 'digital' ),
'meta' => array( '2023–25', 'Hospitality' ),
'desc' => 'Always-on social design for Radisson Blu — restaurant promotions, seasonal campaigns, F&B menus and offers across Eid, Ramadan and standing promotions.',
'scope' => array( 'Social design', 'F&B campaigns', 'Seasonal artwork', 'Monthly content' ),
'images' => array( 'projects/radisson-1.jpg' ),
'brief' => 'Always-on social and F&B campaigns.',
'slug' => 'radisson',
'home' => array(
),
), array(
'title' => 'Briefill',
'cat' => 'Branding · Identity',
'filters' => array( 'branding' ),
'meta' => array( '2024', 'B2B' ),
'desc' => 'Complete brand identity for Briefill — logo system, stationery, signage, brand book and content frameworks under the line "Crafting Excellence Together."',
'scope' => array( 'Brand naming review', 'Identity system', 'Stationery', 'Signage', 'Brand book' ),
'images' => array( 'projects/briefill-1.jpg' ),
'brief' => 'Identity and brand book for Briefill.',
'slug' => 'briefill',
'home' => array(
),
), array(
'title' => 'Finest Business · أرقى الأعمال',
'cat' => 'Branding · Identity',
'filters' => array( 'branding' ),
'meta' => array( '2024', 'B2B' ),
'desc' => 'Arabic-led brand identity and applications for Finest Business — calligraphic wordmark, signage system, stationery and folder collateral in burgundy and green palettes.',
'scope' => array( 'Arabic wordmark', 'Identity system', 'Signage', 'Stationery', 'Print collateral' ),
'images' => array( 'projects/finest-1.jpg' ),
'brief' => 'Arabic-led identity for Finest Business.',
'slug' => 'finest',
'home' => array(
),
), array(
'title' => 'Pointsgram · Web Platform',
'cat' => 'Digital · Web',
'filters' => array( 'digital' ),
'meta' => array( '2024', 'Tech' ),
'desc' => 'Web design and development for the Pointsgram rewards platform — landing pages, FAQ system, brand-led microsites and ongoing visual support.',
'scope' => array( 'UX / UI design', 'Web development', 'Landing pages', 'Visual support' ),
'images' => array( 'projects/pointsgram-1.jpg' ),
'brief' => 'Rewards platform web design and microsites.',
'slug' => 'pointsgram',
'home' => array(
),
) ),
);
