<?php
/** Section-level page editors. */
defined( 'ABSPATH' ) || exit;
add_action( 'acf/init', function () {
acf_add_local_field_group( array( 'key' => 'group_bl_sections_home', 'title' => 'Home sections', 'location' => array( array( array( 'param' => 'page_template', 'operator' => '==', 'value' => 'template-home.php' ) ), array( array( 'param' => 'page_type', 'operator' => '==', 'value' => 'front_page' ) ) ), 'fields' => array(
array( 'key' => 'field_bl_home_heading_1', 'name' => 'bl_home_heading_1', 'label' => 'Hero — Heading', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_home_heading_2', 'name' => 'bl_home_heading_2', 'label' => 'About — Heading', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_home_heading_3', 'name' => 'bl_home_heading_3', 'label' => 'Services — Heading', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_home_heading_4', 'name' => 'bl_home_heading_4', 'label' => 'Projects — Heading', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_home_heading_5', 'name' => 'bl_home_heading_5', 'label' => 'Process — Heading', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_home_heading_6', 'name' => 'bl_home_heading_6', 'label' => 'Clients — Heading', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_home_quote', 'name' => 'bl_home_quote', 'label' => 'Quote and attribution', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_home_button_1', 'name' => 'bl_home_button_1', 'label' => 'About — Button', 'type' => 'link', 'return_format' => 'array' ),
array( 'key' => 'field_bl_home_button_2', 'name' => 'bl_home_button_2', 'label' => 'Work — View all button', 'type' => 'link', 'return_format' => 'array' ),
array( 'key' => 'field_bl_home_button_3', 'name' => 'bl_home_button_3', 'label' => 'Work — Contact button', 'type' => 'link', 'return_format' => 'array' ),
array( 'key' => 'field_bl_home_button_4', 'name' => 'bl_home_button_4', 'label' => 'Clients — Button', 'type' => 'link', 'return_format' => 'array' ),
array( 'key' => 'field_bl_home_benefits', 'name' => 'bl_home_benefits', 'label' => 'About — Benefits', 'type' => 'repeater', 'layout' => 'block', 'button_label' => 'Add row', 'sub_fields' => array( array( 'key' => 'field_bl_home_benefits_content', 'name' => 'content', 'label' => 'Content', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ) ) ),
array( 'key' => 'field_bl_home_steps', 'name' => 'bl_home_steps', 'label' => 'Process — Steps', 'type' => 'repeater', 'layout' => 'block', 'button_label' => 'Add row', 'sub_fields' => array( array( 'key' => 'field_bl_home_steps_title', 'name' => 'title', 'label' => 'Title', 'type' => 'text' ), array( 'key' => 'field_bl_home_steps_description', 'name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'new_lines' => '' ) ) )
) ) );
acf_add_local_field_group( array( 'key' => 'group_bl_sections_about', 'title' => 'About sections', 'location' => array( array( array( 'param' => 'page_template', 'operator' => '==', 'value' => 'template-about.php' ) ) ), 'fields' => array(
array( 'key' => 'field_bl_about_hero', 'name' => 'bl_about_hero', 'label' => 'Hero — Heading and introduction', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_about_cta', 'name' => 'bl_about_cta', 'label' => 'CTA — Content', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_about_heading_1', 'name' => 'bl_about_heading_1', 'label' => 'Story — Heading', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_about_heading_2', 'name' => 'bl_about_heading_2', 'label' => 'Pillars — Heading', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_about_button_1', 'name' => 'bl_about_button_1', 'label' => 'CTA — Button', 'type' => 'link', 'return_format' => 'array' ),
array( 'key' => 'field_bl_about_pillars', 'name' => 'bl_about_pillars', 'label' => 'Vision, mission and values', 'type' => 'repeater', 'layout' => 'block', 'button_label' => 'Add row', 'sub_fields' => array( array( 'key' => 'field_bl_about_pillars_icon', 'name' => 'icon', 'label' => 'Icon', 'type' => 'text' ), array( 'key' => 'field_bl_about_pillars_label', 'name' => 'label', 'label' => 'Label', 'type' => 'text' ), array( 'key' => 'field_bl_about_pillars_content', 'name' => 'content', 'label' => 'Content', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ) ) )
) ) );
acf_add_local_field_group( array( 'key' => 'group_bl_sections_projects', 'title' => 'Projects sections', 'location' => array( array( array( 'param' => 'page_template', 'operator' => '==', 'value' => 'template-projects.php' ) ) ), 'fields' => array(
array( 'key' => 'field_bl_projects_hero', 'name' => 'bl_projects_hero', 'label' => 'Hero — Heading and introduction', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_projects_cta', 'name' => 'bl_projects_cta', 'label' => 'CTA — Content', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_projects_button_1', 'name' => 'bl_projects_button_1', 'label' => 'CTA — Button', 'type' => 'link', 'return_format' => 'array' )
) ) );
acf_add_local_field_group( array( 'key' => 'group_bl_sections_clients', 'title' => 'Clients sections', 'location' => array( array( array( 'param' => 'page_template', 'operator' => '==', 'value' => 'template-clients.php' ) ) ), 'fields' => array(
array( 'key' => 'field_bl_clients_hero', 'name' => 'bl_clients_hero', 'label' => 'Hero — Heading and introduction', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_clients_cta', 'name' => 'bl_clients_cta', 'label' => 'CTA — Content', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_clients_quote', 'name' => 'bl_clients_quote', 'label' => 'Quote and attribution', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_clients_button_1', 'name' => 'bl_clients_button_1', 'label' => 'CTA — Button', 'type' => 'link', 'return_format' => 'array' )
) ) );
acf_add_local_field_group( array( 'key' => 'group_bl_sections_contact', 'title' => 'Contact sections', 'location' => array( array( array( 'param' => 'page_template', 'operator' => '==', 'value' => 'template-contact.php' ) ) ), 'fields' => array(
array( 'key' => 'field_bl_contact_hero', 'name' => 'bl_contact_hero', 'label' => 'Hero — Heading and introduction', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_contact_receipt', 'name' => 'bl_contact_receipt', 'label' => 'Form — Success message', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_contact_availability', 'name' => 'bl_contact_availability', 'label' => 'Contact — Availability', 'type' => 'wysiwyg', 'media_upload' => 0, 'toolbar' => 'full', 'instructions' => 'Edit the complete content here. Bold heading text uses the accent color.' ),
array( 'key' => 'field_bl_contact_button_1', 'name' => 'bl_contact_button_1', 'label' => 'Form — Return button', 'type' => 'link', 'return_format' => 'array' ),
) ) );
} );
